[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
cors = *
admin_passwd = $pbkdf2-sha512$600000$xdh7D2GMsVbqHSOEMOZcSw$1fN9sudBBQHRRyVQTJyMGGpQL1Ctjloo54p6aG92aIIudPeGRYJo38y8VHIqPJVCaL2Gr4wKkeLgKn8SOh7fLQ

